language: elixir
elixir: 1.1.0-beta
sudo: false
notifications:
  recipients:
  - bruce.williams@cargosense.com
addons:
  apt:
    packages:
    - texlive-latex-base
otp_release:
- 17.1
- 17.5
- 18.0
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test"
